apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8paj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0058-tenant/tkrw-pr712-0075-0058-app/devfile-sample-8paj@sha256:5e1c1388fae6c0480bb91311f86537db1f4c22f06d3474a850e6911fc3105b5a
        name: my-nodejs
        resources: {}
status: {}
